---
- name: Install rsyslog
  apt:
    name: rsyslog
    state: present
    update_cache: yes

- name: Configure rsyslog to forward logs to Graylog server
  lineinfile:
    path: /etc/rsyslog.d/90-graylog.conf
    line: '*.* @sim.east.codemonkey.science:514;RSYSLOG_SyslogProtocol23Format'
    create: yes
  notify: Restart rsyslogd