---
- name: Copy graylog.service to remote host
  copy:
    src: ./files/graylog-grafana.service
    dest: /etc/systemd/system/graylog.service
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd manager configuration
  systemd:
    daemon_reload: yes

- name: Enable and start graylog service
  systemd:
    name: graylog
    enabled: yes
    state: started